parameters:
#    tool_tool.example.class: Tool\ToolBundle\Example

services:
#    tool_tool.example:
#        class: %tool_tool.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
