TemplateDesigner\LayoutBundle\Entity\Layout:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: name, message: The template name is already used}
        - Callback: [validateCustom]
    properties:
        cssClasses:
            - TemplateDesigner\LayoutBundle\Validator\Constraints\ContainsCorrectClasses: ~