TemplateDesigner\LayoutBundle\Entity\Layout:
    type: entity
    table: layout_designer
    repositoryClass: TemplateDesigner\LayoutBundle\Entity\LayoutRepository
    indexes:
        name:
            columns: [ name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        
    fields:
        name:
            type: string
            length: 250
            nullable: true
        cssClasses:
            type: array
        cssComplementClasses:
            type: string
            length: 500
        tag:
            type: string
            length: 250
        cssId:
            type: string
            length: 250
            nullable: true
        render:
            type: string
            length: 250
            nullable: true
        include:
            type: string
            length: 250
            nullable: true
        custom:
            type: string
            length: 100
        engine: 
            type: string
            length: 250
        position:
            type: smallint
            nullable: true
    oneToMany:
            subs:
                targetEntity: Layout
                mappedBy: root
                cascade: ["persist","merge","remove"]
            children:
                targetEntity: Layout
                mappedBy: parent
                cascade: ["persist","merge","remove"]
            # contents:
            #     targetEntity: ContentSubjectInterface
            #     mappedBy: layout
    manyToOne:
            parent:
                targetEntity: Layout
                inversedBy: children
                cascade: ["persist","merge"]
                joinColumn:
                    name: parent_id
                    referencedColumnName: id
                    onDelete : CASCADE
            root:
                targetEntity: Layout
                inversedBy: subs
                cascade: ["persist","merge"]
                joinColumn:
                    name: root_id
                    referencedColumnName: id
                    onDelete : CASCADE

    lifecycleCallbacks: {  }
