tool_tool:
    resource: "@ToolToolBundle/Resources/config/routing.yml"
    prefix:   /

template_designer_layout:
    resource: "@TemplateDesignerLayoutBundle/Controller/"
    type:     annotation
    prefix:   /




