parameters:
    template_designer.layout_data_collector.template:  "TemplateDesignerLayoutBundle:DataCollector:template"

services:
  layout.twig.extension:
    class: TemplateDesigner\LayoutBundle\Twig\TwigExtension # <--- here
    arguments: ["@doctrine.orm.entity_manager","%template_designer_layout.custom_param_template%"]
    tags:
      - { name: twig.extension }

  layout.params.action_listener:
        class: TemplateDesigner\LayoutBundle\EventListener\ParameterWrapperListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
  layout.annotation.action_listener:
        class: TemplateDesigner\LayoutBundle\EventListener\LayoutAnnotationListener
        arguments: ["@annotation_reader","@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
  layout.data_collector.action_listener:
        class: TemplateDesigner\LayoutBundle\DataCollector\LayoutDataCollector
        tags:
            - { name: data_collector, template: %template_designer.layout_data_collector.template%, id: "layout" }
  route.manager:
        class: TemplateDesigner\LayoutBundle\Service\RouteManager
        arguments: ["@router"]
  template_finder:
        class: TemplateDesigner\LayoutBundle\Service\TemplateFinder
  layout.doctrine.listener:
        class: TemplateDesigner\LayoutBundle\EventListener\LayoutDataListener
        arguments: ["%template_designer_layout.template_engine%"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
  layout.helper:
        class: TemplateDesigner\LayoutBundle\Service\LayoutHelper
        arguments: ["%template_designer_layout.template_engine%"]