Tool\ToolBundle\Entity\Content:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    # manyToOne:
    #         layout:
    #             targetEntity: TemplateDesigner\LayoutBundle\Entity\ContentSubjectInterface
    #             inversedBy: contents
    lifecycleCallbacks: {  }