Tool\ToolBundle\Entity\MyLayout:
    type: entity
    table: null
    # oneToMany:
    #         contents:
    #             targetEntity: Content
    #             mappedBy: layout
    lifecycleCallbacks: {  }
